apiVersion: speckle.systems/v1alpha1
kind: SpeckleFunction
metadata:
  name: basic
spec:
  params: []
  build:
    dockerfile:
      path: '.'
  command: [] # use default command from Dockerfile
  args: []
