name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions: {} # no permissions by default; to be individually overridden by the jobs below
concurrency:
  group: ${{ github.workflow }}-main-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pre-commit-and-test:
    name: Run Tests
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
    steps:
      - uses: useblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b # v1.0.0-beta
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0 # zizmor: ignore[cache-poisoning] see package-manager-cache below
        with:
          node-version: 22
          cache: yarn
          package-manager-cache: ${{ github.event_name == 'pull_request' }} # we only cache on pull requests to avoid cache poisoning attacks.
      - name: Yarn Install
        run: yarn install
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - name: Tests
        run: yarn test
        continue-on-error: true # ignore test failures for now
  zizmor:
    name: GitHub Actions Linter
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: useblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b # v1.0.0-beta
        with:
          persist-credentials: false

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          advanced-security: false
